### ISSUE TITLE
nw_protocol_get_quic_image_block_invoke dlopen libquic failed

### ISSUE THREAD

**Issue by tamc** [ctreffs/SwiftSimctl#10] opened 2020-11-26 09:51 UTC
This library looks like it would solve one of the aspects of iOS testing that causes me pain -- thank you.

Unfortunately when I call `simctl.setPrivacy` in my tests I then see in the logs:

    nw_protocol_get_quic_image_block_invoke dlopen libquic failed

And shortly after, the test process crashes. If I comment out the call to simctl.setPrivacy, the test passes.

I will try and create a small test app to reproduce the problem. But, if you have any suggestions as to where to look in the mean time, they would be greatly appreciated.

**Comment by ctreffs** [comment] 2020-11-26 10:00
Hi,

my guess would be you did not allow the client-server communication in your firewall settings.
SwiftSimctl uses a local server (default port 8080) to communicate it's actions with the tests. 
On first startup you will be asked if you like to allow incomming connections. If you somehow missed that or denied it entirely it could be that the setting was persisted as denied.
Try to have a look at `System Settings > Security > Firewall > Firewall-Options` and see if `SimctlCLI` has incomming connections allowed. If not, add and allow it. 
I've attached a screenshot (sorry for the German localization) to make this a little clearer.

Hope this helps, let me know.

![Bildschirmfoto 2020-11-26 um 10 55 56](https://user-images.githubusercontent.com/1262900/100336389-693c5300-2fd6-11eb-91c7-7814cb4a9fb5.png)

**Comment by tamc** [comment] 2020-11-26 10:21
Thank you for responding so quickly with your suggestion @ctreffs.

Unfortunately it isn't that: I have switched off the firewall.

If I run the test with the SimctlCLI server switched off I get a different (and expected) error `Could not connect to the server.`.

If I run the test with the SimctlCLI server switched on, I get `nw_protocol_get_quic_image_block_invoke dlopen libquic failed` and a crash.

I will keep trying to work on a smaller test case so that hopefully I can discover the cause of the problem and then share it.

**Comment by ctreffs** [comment] 2020-11-26 10:25
Ok, thanks, but from [googling your error](www.google.com/search?as_q=&as_epq=nw_protocol_get_quic_image_block_invoke+dlopen+libquic+failed) this seems to be a wider spread issue that does not necessarily even be connected to SwiftSimctl. It seems to be related to UDP and this library though <https://github.com/devsisters/libquic>.

Let me know what you find and good look 👍

**Comment by tamc** [comment] 2020-11-26 17:47
Yes. The issue is triggered by the SimctlCLI call, but it looks like the root cause is somewhere else.

I have got as far as establishing that there is no problem if the simulator is running an iOS 12.1 device, but that the problem is triggered on an iOS 14.2 device.

I will keep digging.

**Comment by tamc** [comment] 2020-12-01 14:17
So. It seems the error in the logs may be misleading, it isn't a bug in SwiftSimctl, and it may or may not be a bug in the underlying simctl command.

It turns out that, for me, when running a XCode 12.2:

1. Create a fresh app
2. Start the app running in the simulator (in my case, running iOS 14.2)
3. Issue a command of the form `xcrun simctl privacy <simulator id> grant photos <bundle id>`
4. Then the app immediately dies.

This prevents simctl privacy commands from being run during a test, though it isn't a fault with the SwiftSimctl code.

**Comment by ctreffs** [comment] 2020-12-02 08:27
Hope you get it to work on your side soon 🤞 
Since it's not directly caused by SwiftSimctl, as far as we know, I will close the issue for now.

**Closed by ctreffs** 2020-12-02 08:27 UTC
Labels: question
